In [1]:
import numpy as np
np.__version__ # check version

'1.14.2'

In [2]:
# Make a list of numbers going from 0 to 9
L = list(range(10))

In [5]:
# Print L
print(L)

# Use list comprehension to convert from [int] to [str]
L_Str = [str(c) for c in L]

# Print L_Str
print(L_Str)

# Should print 'int' 10 times
print([type(c) for c in L])

# Should print 'str' 10 times
print([type(c) for c in L_Str])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
[<class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>]
[<class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>]


- Numpy Arrays are homogenous (1 type only)
- Create Numpy Arrays filled with zeros by calling np.zeros(size, dtype='int'/float)

In [6]:
# Make a NumPy Array of length 10 filled with 0s
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
# Make a Matrix of dimensions 3 x 5 filled with 1s that are all floats
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
# Create a Matrix with a predefined value of size 3 x 5
np.full((3,5), 1.23, dtype=float)

array([[1.23, 1.23, 1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23, 1.23, 1.23]])

In [10]:
# Create a NumPy Array with a set sequence
np.arange(0, 20, 2) # Gets range [0, 20) skipping by 2s.

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
# Create an array of even space between the given range of values
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
# Create a 3x3 array with mean 0 and std. deviation 1 in a given dimension
np.random.normal(0, 1, (3,3))

array([[ 0.71851049,  1.19258732, -2.41802307],
       [-0.27375918,  1.09760179,  2.19292835],
       [-1.12469928,  0.48638925,  0.53518067]])

In [13]:
# Create a 5x4 array with mean 5 and std. deviation 4 in a given dimension
np.random.normal(5, 4, (5,4))

array([[ 4.38092254,  8.21158285,  9.11633559,  5.93666248],
       [ 2.77547266, 11.42033701,  1.56420091,  6.02458955],
       [ 5.4312792 ,  5.26307045,  3.06359387,  2.44370763],
       [ 6.24833573, 12.64765175,  6.39081885,  7.83186312],
       [ 5.51353344,  2.56656191, 10.45213586,  6.70830204]])

In [14]:
# Create an Identity Matrix of Dimension 4
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
# Set a random seed
np.random.seed(0)

In [19]:
# One dimensional random array of size 6 and max element 10
x1 = np.random.randint(10, size=6)

# Two dimensional random array of size (3,4) and max element 20
x2 = np.random.randint(20, size=(3,4))

# Three dimensional random array of size (3,4,5) and max element 30
x3 = np.random.randint(30, size=(3,4,5))

In [22]:
def print_stats_for_np_array(nparray):
    print('Array:', nparray)
    print('Array.ndim:', nparray.ndim)
    print('Array.shape:', nparray.shape)
    print('Array.size:', nparray.size)

In [23]:
print_stats_for_np_array(x1)

Array: [3 5 2 4 7 6]
Array.ndim: 1
Array.shape: (6,)
Array.size: 6


In [24]:
print_stats_for_np_array(x2)

Array: [[12  1  6  7]
 [14 17  5 13]
 [ 8  9 19 16]]
Array.ndim: 2
Array.shape: (3, 4)
Array.size: 12


In [25]:
print_stats_for_np_array(x3)

Array: [[[19  5 15 15  0]
  [18  3 24 17 19]
  [29 19 19 14  7]
  [ 0  1  9 25  0]]

 [[10 20 23  3 11]
  [18 23 28  2  0]
  [ 0  4 21  5  6]
  [ 8 20 17 15  4]]

 [[ 9 10 26 24  1]
  [ 1  7  9 25  3]
  [ 6 23 11 14 18]
  [27  0 14  3 21]]]
Array.ndim: 3
Array.shape: (3, 4, 5)
Array.size: 60


### Array Indexing in NumPy

In [26]:
x1 = np.array([4, 3, 4, 4, 8, 4])
x1

array([4, 3, 4, 4, 8, 4])

In [30]:
# Retuen first value
x1[0]

4

In [31]:
# Return last value
x1[-1]

4

In [32]:
# Return second last value
x1[-2]

8

In [33]:
x2

array([[12,  1,  6,  7],
       [14, 17,  5, 13],
       [ 8,  9, 19, 16]])

In [35]:
# Third Row and 4th Column
x2[2,3]

16

In [36]:
# Change value at first row and first column of x2 to 11
x2[0,0] = 11

In [37]:
# Show x2 Now
x2

array([[11,  1,  6,  7],
       [14, 17,  5, 13],
       [ 8,  9, 19, 16]])

#### Wootwoot!! :P Yayayayayayay!!!!!!!!!!

### Array Slicing in NumPy

In [38]:
x = np.arange(10)

In [39]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
# From start to index 5 exclusive
x[:5]

array([0, 1, 2, 3, 4])

In [42]:
# From index 5 to end, inclusive
x[5:]

array([5, 6, 7, 8, 9])

In [45]:
# From 5th to 7th Position, inclusive
x[4:8]

array([4, 5, 6, 7])

In [47]:
# Return every 4th element
x[ : : 4]

array([0, 4, 8])

In [48]:
# Return elements from index 2 by steps of 3
x[2::4]

array([2, 6])

In [49]:
# Return elements upto index 5 by steps of 3
x[:5:3]

array([0, 3])

In [ ]:
# Re